# file      : buildfile
# copyright : Copyright (c) 2018-2019 Code Synthesis Ltd
# license   : cURL License; see accompanying COPYING file
#
./: {*/ -build/} doc{COPYING INSTALL README} manifest

# Don't install tests or the INSTALL file.
#
tests/:          install = false
doc{INSTALL}@./: install = false
