# file      : curl/buildfile
# license   : curl License; see accompanying COPYING file

import libs  = libcurl%lib{curl}
import libs += libca-certificates-curl%lib{ca-certificates-curl}

exe{curl}: h{**} c{** -src/tool_main -lib/**} $libs

tclass = $c.target.class
tsys   = $c.target.system

# Build options.
#
c.poptions += -DHAVE_CONFIG_H

switch $tclass, $tsys
{
  case 'windows', 'win32-msvc'
    c.poptions += -DWIN32
}

c.poptions =+ "-I$src_base" "-I$src_base/src" "-I$src_base/lib"

switch $c.class
{
  case 'gcc'
  {
    # Disable warnings that pop up with -Wall -Wextra. Upstream doesn't seem
    # to care about these and it is not easy to disable specific warnings in a
    # way that works across compilers/version (some -Wno-* options are only
    # recognized in newer versions).
    #
    c.coptions += -Wno-all -Wno-extra -Wno-deprecated-declarations
  }
  case 'msvc'
  {
    # Disable warnings that pop up with /W3.
    #
    c.coptions += /wd4996
  }
}

switch $tclass, $tsys
{
  case 'linux' | 'bsd'
    c.libs += -pthread

  case 'windows', 'mingw32'
    c.libs+= -lws2_32

  case 'windows'
    c.libs += ws2_32.lib
}
